# full precision Model Setup, no flashatten and autocast
defaults:
  - default

model_name: ./Chk/borzoi_pretrain

## technical setup
flashed: False  # whether to use FlashAttention, in finetune setting, we should disable this
use_autocast: False  # whether to use autocast, if using FlashAttention, always set to True, else, default as False

## fine tune setting

## Available finetune_method
### `lora`: low rank approximation, adding some trainable layers to the model and fix the rest (using peft LoraConfig)
### `finetune_layers`: provide some trainable layers and only train these layers
### `cont_from_pretrain`: just load the parameters from the pretrained model and continue training 
finetune_method: cont_from_pretrain
finetune_param: null

# new output head setting for the model
output_heads: # set up the prediction head name and trial number
  use_cell_encoder: False  # whether to use shared cell encoder for the output heads, if True, the output will be calculated as celltype embedding then shared task output, else, directly output separate celltype * modality
