defaults:
  - default


lr: 0.00006 # learning rate
lr_warmup_step: 10000  # gradually increase lr from 0 to `lr` in given optimization steps
batch_size: 2 # batch size for one single GPU
total_epoch: 180  # maximum training epoch number
accum_step: 1 # gradient accumulation step (effective batchsize=world_size * batch_size * accum_step)
clip_grad_norm: 0.15 # gradient clipping norm, 0.15 as in borzoi
seed: 42  # random seed for reproduciblility


