# Training setup
world_size: 4 # how many GPUs to use for training, 1 for single GPU training, >1 for DDP training
MASTER_ADDR: localhost # master address for DDP training
MASTER_PORT: 12320 # master port for DDP training