defaults:
  - default

world_size: 3

# Override dataloader for single-worker mode
dataloader_params:
  batch_size: ${training.batch_size}
  pin_memory: False
  num_workers: 0
  persistent_workers: False

batch_size: 2

accum_step: 4