# Training setup

## basic hardware setup
world_size: 4 # how many GPUs to use for training, 1 for single GPU training, >1 for DDP training
gpu_id: null  # when world size > 1, even if specified, will not be used
MASTER_ADDR: localhost # master address for DDP training
MASTER_PORT: 12320 # master port for DDP training

## model training optimizing
use_grad_compression: False  # whether to use gradient compression (PowerSGD) to reduce GPU communication time. Need to make sure that this is the main training bottle neck
deepspeed: False  # whether to use deepspeed

## training stage setting
load_checkpoint: null # path to the checkpoint to load (if using deepspeed, then the checkpoint tag), if not given, will start from scratch, else, will resume training from the given checkpoint
test_only: False # whether to only run the test stage, if True, load_checkpoint must be given
finetune: True # whether to finetune the model

## training hyperparameter
lr: 1e-4 # maximum learning rate
lr_warmup_step: 10000  # gradually increase lr from 0 to `lr` in given optimization steps
batch_size: 3 # batch size for one single GPU
total_epoch: 200  # maximum training epoch number
accum_step: 2 # gradient accumulation step (effective batchsize=world_size * batch_size * accum_step)
clip_grad_norm: 0.1 # gradient clipping norm, 0.15 as in borzoi
seed: 42  # random seed for reproduciblility

## model head setup
use_head: # list of heads to use for training
  - regression

## loss setup
# loss: poisson # the name of the loss function (now support: poisson, poisson_mn)
# loss_params:
#   log_input: False
#   eps: 1e-7
#   reduction: mean

loss: 
  poisson_mn: # the name of the loss function (now support: poisson, poisson_mn, cross_cell_mn)
    loss_head: regression # the head to use for the loss
    loss_weight: 1.0 # the weight of the loss
    params:
      total_weight: 1
      weight_range: 1
      eps: 1e-7
      reduction: mean
  cross_cell_mn:
    loss_head: regression # the head to use for the loss
    loss_weight: 1.0 # the weight of the loss
    params:
      total_weight: 1
      eps: 1e-7
      reduction: mean
  transcripts_poisson_mn:
    loss_head: regression # the head to use for the loss
    loss_weight: 1.0 # the weight of the loss
    params:
      total_weight: 1
      weight_range: 1
      eps: 1e-7
      reduction: mean
  transcripts_cross_cell_mn:
    loss_head: regression # the head to use for the loss
    loss_weight: 1.0 # the weight of the loss
    params:
      total_weight: 1
      eps: 1e-7
      reduction: mean

## optimizer setup
add_opt_group: True # whether to use optimizer parameter groups
optimizer: AdamW # optimizer to use, the name should be in the torch.optim package
optimizer_params: # optimizer parameters
  lr: ${training.lr}

## scheduler setup
scheduler: WarmupThenCosineDecay
scheduler_params:
  num_warmup_steps: ${training.lr_warmup_step}
  num_training_steps: 84200
# scheduler: WarmupThenReduceLROnPlateau # learning rate scheduler to use
# scheduler_params: # scheduler parameters
#   warmup_steps: ${training.lr_warmup_step}
#   init_lr: ${training.min_lr}
#   peak_lr: ${training.lr}
#   plateau_kwargs:
#     mode: min # mode to use, 'min' or 'max'
#     factor: 0.8 # factor to reduce the learning rate by
#     patience: 5 # number of epochs to wait before reducing the learning rate
#     min_lr: 1e-6 # the minimum learning rate

## dataloader setup
dataloader_params:  # dataloader parameters, should be accepted by torch.utils.data.DataLoader
  batch_size: ${training.batch_size}
  pin_memory: True
  num_workers: 12
  persistent_workers: True

torchrun: false